import type {
  User,
  Cartao,
  TipoDespesa,
  Despesa,
  AuditoriaEntry,
} from "./types";


// ─── Dados ERP (Empresas, Fornecedores, etc) ───────────────────────────────

export const mockEmpresas = [
  { id: "1", nome: "RJ Compressores - São Paulo" },
  { id: "2", nome: "RJ Compressores - Rio de Janeiro" },
  { id: "3", nome: "RJ Compressores - Belo Horizonte" },
];

export const mockFornecedores = [
  { id: "101", nome: "Fornecedor A - Compressor" },
  { id: "102", nome: "Fornecedor B - Peças" },
  { id: "103", nome: "Fornecedor C - Serviços" },
  { id: "104", nome: "Fornecedor D - Manutenção" },
];

export const mockCondicoesPagamento = [
  { id: "1", nome: "À Vista" },
  { id: "2", nome: "30 dias" },
  { id: "3", nome: "60 dias" },
  { id: "4", nome: "90 dias" },
];

export const mockOperacoesFinanceiras = [
  { id: "1", nome: "Venda" },
  { id: "2", nome: "Devolução" },
  { id: "3", nome: "Ajuste" },
  { id: "4", nome: "Crédito" },
  { id: "5", nome: "Débito" },
];

export const mockMoedas = [
  { id: "1", nome: "Real (BRL)", codigo: "BRL" },
  { id: "2", nome: "Dólar (USD)", codigo: "USD" },
  { id: "3", nome: "Euro (EUR)", codigo: "EUR" },
];


export const mockUsers: User[] = [
  {
    id: "u1",
    nome: "Administrador do Sistema",
    email: "admin@rjcompressores.com.br",
    telefone: "(21) 99999-0001",
    usuario: "admin",
    perfil: "administrador",
    ativo: true,
    senha: "12345",
    primeiroAcesso: true,
    empresaId: "1",
    fornecedorId: "101",
    condicaoPagamentoId: "1",
    operacaoFinanceiraId: "5",
    moedaId: "1",
  },
  {
    id: "u2",
    nome: "Carlos Eduardo Silva",
    email: "carlos.silva@rjcompressores.com.br",
    telefone: "(21) 99999-0002",
    usuario: "carlos",
    perfil: "tecnico",
    ativo: true,
    gestorId: "u4",
    senha: "12345",
    primeiroAcesso: false,
    empresaId: "1",
    fornecedorId: "102",
    condicaoPagamentoId: "1",
    operacaoFinanceiraId: "5",
    moedaId: "1",
  },
  {
    id: "u3",
    nome: "Marcos Antônio Pereira",
    email: "marcos.pereira@rjcompressores.com.br",
    telefone: "(21) 99999-0003",
    usuario: "marcos",
    perfil: "tecnico",
    ativo: true,
    gestorId: "u4",
    senha: "12345",
    primeiroAcesso: false,
    empresaId: "1",
    fornecedorId: "103",
    condicaoPagamentoId: "1",
    operacaoFinanceiraId: "5",
    moedaId: "1",
  },
  {
    id: "u4",
    nome: "Roberto Mendes",
    email: "roberto.mendes@rjcompressores.com.br",
    telefone: "(21) 99999-0004",
    usuario: "gestor",
    perfil: "gestor",
    ativo: true,
    senha: "12345",
    primeiroAcesso: false,
  },
  {
    id: "u5",
    nome: "Ana Paula Financeiro",
    email: "ana.financeiro@rjcompressores.com.br",
    telefone: "(21) 99999-0005",
    usuario: "financeiro",
    perfil: "financeiro",
    ativo: true,
    senha: "12345",
    primeiroAcesso: false,
  },
];

export const mockCartoes: Cartao[] = [
  {
    id: "c1",
    usuarioId: "u2",
    nome: "Cartão Corporativo Itaú",
    banco: "Itaú",
    bandeira: "Visa",
    ultimos4: "4521",
    contaBancariaId: "10",
    padrao: true,
    ativo: true,
  },
  {
    id: "c2",
    usuarioId: "u2",
    nome: "Cartão Bradesco",
    banco: "Bradesco",
    bandeira: "Mastercard",
    ultimos4: "7890",
    contaBancariaId: "11",
    padrao: false,
    ativo: true,
  },
  {
    id: "c3",
    usuarioId: "u3",
    nome: "Cartão Corporativo BB",
    banco: "Banco do Brasil",
    bandeira: "Visa",
    ultimos4: "3344",
    contaBancariaId: "12",
    padrao: true,
    ativo: true,
  },
];

export const mockTiposDespesa: TipoDespesa[] = [
  {
    id: "td1",
    nome: "Hotel",
    ativo: true,
    limiteMaximo: 160,
    exigeAprovacaoAcimaLimite: true,
    exigeComprovante: true,
    contaContabilDespesaId: "3001",
    historicoDespesaId: "H01",
    centroCustoId: "CC01",
    tipoDocumentoPadrao: "NF",
    observacaoPadrao: "Hospedagem durante atendimento externo",
  },
  {
    id: "td2",
    nome: "Almoço",
    ativo: true,
    limiteMaximo: 42,
    exigeAprovacaoAcimaLimite: true,
    exigeComprovante: true,
    contaContabilDespesaId: "3002",
    historicoDespesaId: "H02",
    centroCustoId: "CC01",
    tipoDocumentoPadrao: "Cupom Fiscal",
    observacaoPadrao: "",
  },
  {
    id: "td3",
    nome: "Café da Manhã",
    ativo: true,
    limiteMaximo: 22.5,
    exigeAprovacaoAcimaLimite: true,
    exigeComprovante: false,
    contaContabilDespesaId: "3002",
    historicoDespesaId: "H02",
    centroCustoId: "CC01",
    tipoDocumentoPadrao: "Cupom Fiscal",
    observacaoPadrao: "",
  },
  {
    id: "td4",
    nome: "Jantar",
    ativo: true,
    limiteMaximo: 42,
    exigeAprovacaoAcimaLimite: true,
    exigeComprovante: true,
    contaContabilDespesaId: "3002",
    historicoDespesaId: "H02",
    centroCustoId: "CC01",
    tipoDocumentoPadrao: "Cupom Fiscal",
    observacaoPadrao: "",
  },
  {
    id: "td5",
    nome: "Confraternização",
    ativo: true,
    limiteMaximo: undefined,
    exigeAprovacaoAcimaLimite: false,
    exigeComprovante: true,
    contaContabilDespesaId: "3003",
    historicoDespesaId: "H03",
    centroCustoId: "CC02",
    tipoDocumentoPadrao: "NF",
    observacaoPadrao:
      "Para campanhas de vendas deverá ser utilizado o tipo Confraternização.",
  },
  {
    id: "td6",
    nome: "Combustível",
    ativo: true,
    limiteMaximo: undefined,
    exigeAprovacaoAcimaLimite: false,
    exigeComprovante: true,
    contaContabilDespesaId: "3004",
    historicoDespesaId: "H04",
    centroCustoId: "CC01",
    tipoDocumentoPadrao: "Cupom",
    observacaoPadrao: "",
  },
  {
    id: "td7",
    nome: "Compra de Material Avulso",
    ativo: true,
    limiteMaximo: undefined,
    exigeAprovacaoAcimaLimite: false,
    exigeComprovante: true,
    contaContabilDespesaId: "3005",
    historicoDespesaId: "H05",
    centroCustoId: "CC03",
    tipoDocumentoPadrao: "NF",
    observacaoPadrao: "",
  },
];

export const mockDespesas: Despesa[] = [
  {
    id: "d1",
    tecnicoId: "u2",
    dataDespesa: "2026-06-01",
    cliente: "Petrobrás",
    numeroOS: "OS-10451",
    tipoDespesaId: "td1",
    valor: 145.0,
    documento: "NF-12345",
    cartaoId: "c1",
    observacao: "Hospedagem na Av. Rio Branco",
    statusAprovacao: "AguardandoGestor",
    statusERP: "EnviadoAguardandoGestor",
    erpId: "ERP-9901",
    dataCriacao: "2026-06-01T10:00:00Z",
    dataAtualizacao: "2026-06-01T10:00:00Z",
  },
  {
    id: "d2",
    tecnicoId: "u2",
    dataDespesa: "2026-06-02",
    cliente: "Petroquímica",
    numeroOS: "OS-10452",
    tipoDespesaId: "td2",
    valor: 55.0,
    documento: "Cupom-999",
    cartaoId: "c1",
    observacao: "Almoço com cliente",
    statusAprovacao: "AguardandoGestor",
    statusERP: "EnviadoAguardandoGestor",
    erpId: "ERP-9902",
    dataCriacao: "2026-06-02T12:00:00Z",
    dataAtualizacao: "2026-06-02T12:00:00Z",
  },
  {
    id: "d3",
    tecnicoId: "u3",
    dataDespesa: "2026-06-01",
    cliente: "Vale S.A.",
    numeroOS: "OS-10453",
    tipoDespesaId: "td6",
    valor: 280.0,
    documento: "Cupom-1001",
    cartaoId: "c3",
    observacao: "Abastecimento viagem Niterói",
    statusAprovacao: "AprovadoGestor",
    statusERP: "AprovadoGestorERPAtualizado",
    erpId: "ERP-9903",
    gestorAprovadorId: "u4",
    dataAprovacao: "2026-06-01T15:00:00Z",
    dataCriacao: "2026-06-01T08:00:00Z",
    dataAtualizacao: "2026-06-01T15:00:00Z",
  },
  {
    id: "d4",
    tecnicoId: "u2",
    dataDespesa: "2026-05-28",
    cliente: "Braskem",
    numeroOS: "OS-10440",
    tipoDespesaId: "td1",
    valor: 200.0,
    documento: "NF-11000",
    cartaoId: "c2",
    observacao: "Hotel acima do limite - viagem emergência",
    statusAprovacao: "Reprovado",
    statusERP: "ReprovadoERPAtualizado",
    erpId: "ERP-9900",
    gestorAprovadorId: "u4",
    dataAprovacao: "2026-05-29T09:00:00Z",
    justificativaReprovacao: "Valor acima do limite sem justificativa prévia.",
    dataCriacao: "2026-05-28T18:00:00Z",
    dataAtualizacao: "2026-05-29T09:00:00Z",
  },
  {
    id: "d5",
    tecnicoId: "u3",
    dataDespesa: "2026-06-03",
    cliente: "TechOil",
    numeroOS: "OS-10460",
    tipoDespesaId: "td3",
    valor: 18.0,
    cartaoId: "c3",
    observacao: "Café antes do atendimento",
    statusAprovacao: "AguardandoGestor",
    statusERP: "ErroEnvioERP",
    dataCriacao: "2026-06-03T07:00:00Z",
    dataAtualizacao: "2026-06-03T07:05:00Z",
  },
];

export const mockAuditoria: AuditoriaEntry[] = [
  {
    id: "a1",
    usuarioId: "u2",
    acao: "Despesa criada",
    entidade: "Despesa",
    entidadeId: "d1",
    detalhes: "Despesa OS-10451 criada. Enviada ao ERP.",
    data: "2026-06-01T10:00:00Z",
  },
  {
    id: "a2",
    usuarioId: "u4",
    acao: "Despesa aprovada",
    entidade: "Despesa",
    entidadeId: "d3",
    detalhes: "Gestor aprovou despesa OS-10453.",
    data: "2026-06-01T15:00:00Z",
  },
  {
    id: "a3",
    usuarioId: "u4",
    acao: "Despesa reprovada",
    entidade: "Despesa",
    entidadeId: "d4",
    detalhes:
      "Gestor reprovou despesa OS-10440. Motivo: Valor acima do limite sem justificativa prévia.",
    data: "2026-05-29T09:00:00Z",
  },
  {
    id: "a4",
    usuarioId: "u2",
    acao: "Despesa criada",
    entidade: "Despesa",
    entidadeId: "d2",
    detalhes: "Despesa OS-10452 criada. Enviada ao ERP.",
    data: "2026-06-02T12:00:00Z",
  },
];
